name: SUL Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" # Versão estável compatível com Fedora 43

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instalando dependências do sistema necessárias para psycopg2 e fdb
        sudo apt-get install -y libpq-dev firebird-dev
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        pip install flake8
        # Para garantir que o código segue o padrão PEP8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics